# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TopicEventBus', :path => '../'

  target 'ExampleProjectTests' do
    inherit! :search_paths
    pod 'TopicEventBus', :path => '../'
  end

  target 'ExampleProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
